In [1]:
# Install the library
!pip install jovian --upgrade --quiet

In [2]:
import jovian

In [3]:
jovian.commit(project='india-covid-data-analysis')

[jovian] Attempting to save notebook..
[jovian] Creating a new project "blazing-storm/india-covid-data-analysis"
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/blazing-storm/india-covid-data-analysis

'https://jovian.ml/blazing-storm/india-covid-data-analysis'

In [4]:
from urllib.request import urlretrieve

In [5]:
urlretrieve('https://covid.ourworldindata.org/data/owid-covid-data.csv', 'owid-covid-data.csv')

('owid-covid-data.csv', <http.client.HTTPMessage at 0x7ff20d321550>)

In [6]:
import pandas as pd

In [7]:
world_df = pd.read_csv('owid-covid-data.csv')

In [8]:
world_df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2019-12-31,0.0,0.0,NaN,0.0,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
1,AFG,Asia,Afghanistan,2020-01-01,0.0,0.0,NaN,0.0,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
2,AFG,Asia,Afghanistan,2020-01-02,0.0,0.0,NaN,0.0,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
3,AFG,Asia,Afghanistan,2020-01-03,0.0,0.0,NaN,0.0,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
4,AFG,Asia,Afghanistan,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45634,NaN,NaN,International,2020-09-19,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45635,NaN,NaN,International,2020-09-20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45636,NaN,NaN,International,2020-09-21,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45637,NaN,NaN,International,2020-09-22,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45638,NaN,NaN,International,2020-09-23,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
world_df[world_df.location == 'India']

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
19060,IND,Asia,India,2019-12-31,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19061,IND,Asia,India,2020-01-01,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19062,IND,Asia,India,2020-01-02,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19063,IND,Asia,India,2020-01-03,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19064,IND,Asia,India,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19323,IND,Asia,India,2020-09-19,5308014.0,93337.0,92575.714,85619.0,1247.0,1163.857,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19324,IND,Asia,India,2020-09-20,5400619.0,92605.0,92323.286,86752.0,1133.0,1166.571,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19325,IND,Asia,India,2020-09-21,5487580.0,86961.0,91593.286,87882.0,1130.0,1165.714,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19326,IND,Asia,India,2020-09-22,5562663.0,75083.0,90346.714,88935.0,1053.0,1165.571,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19327,IND,Asia,India,2020-09-23,5646010.0,83347.0,89378.714,90020.0,1085.0,1136.286,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64

In [12]:
india_df = world_df[world_df.location == 'India']

In [13]:
india_df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
19060,IND,Asia,India,2019-12-31,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19061,IND,Asia,India,2020-01-01,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19062,IND,Asia,India,2020-01-02,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19063,IND,Asia,India,2020-01-03,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19064,IND,Asia,India,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19323,IND,Asia,India,2020-09-19,5308014.0,93337.0,92575.714,85619.0,1247.0,1163.857,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19324,IND,Asia,India,2020-09-20,5400619.0,92605.0,92323.286,86752.0,1133.0,1166.571,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19325,IND,Asia,India,2020-09-21,5487580.0,86961.0,91593.286,87882.0,1130.0,1165.714,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19326,IND,Asia,India,2020-09-22,5562663.0,75083.0,90346.714,88935.0,1053.0,1165.571,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19327,IND,Asia,India,2020-09-23,5646010.0,83347.0,89378.714,90020.0,1085.0,1136.286,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64

In [14]:
india_df = india_df.copy()

In [15]:
india_df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
19060,IND,Asia,India,2019-12-31,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19061,IND,Asia,India,2020-01-01,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19062,IND,Asia,India,2020-01-02,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19063,IND,Asia,India,2020-01-03,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19064,IND,Asia,India,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19323,IND,Asia,India,2020-09-19,5308014.0,93337.0,92575.714,85619.0,1247.0,1163.857,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19324,IND,Asia,India,2020-09-20,5400619.0,92605.0,92323.286,86752.0,1133.0,1166.571,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19325,IND,Asia,India,2020-09-21,5487580.0,86961.0,91593.286,87882.0,1130.0,1165.714,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19326,IND,Asia,India,2020-09-22,5562663.0,75083.0,90346.714,88935.0,1053.0,1165.571,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
19327,IND,Asia,India,2020-09-23,5646010.0,83347.0,89378.714,90020.0,1085.0,1136.286,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64

In [16]:
india_df.reset_index(inplace = True)

In [17]:
india_df

,index,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,19060,IND,Asia,India,2019-12-31,0.0,0.0,NaN,0.0,0.0,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
1,19061,IND,Asia,India,2020-01-01,0.0,0.0,NaN,0.0,0.0,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
2,19062,IND,Asia,India,2020-01-02,0.0,0.0,NaN,0.0,0.0,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
3,19063,IND,Asia,India,2020-01-03,0.0,0.0,NaN,0.0,0.0,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
4,19064,IND,Asia,India,2020-01-04,0.0,0.0,NaN,0.0,0.0,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,19323,IND,Asia,India,2020-09-19,5308014.0,93337.0,92575.714,85619.0,1247.0,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
264,19324,IND,Asia,India,2020-09-20,5400619.0,92605.0,92323.286,86752.0,1133.0,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
265,19325,IND,Asia,India,2020-09-21,5487580.0,86961.0,91593.286,87882.0,1130.0,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
266,19326,IND,Asia,India,2020-09-22,5562663.0,75083.0,90346.714,88935.0,1053.0,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
267,19327,IND,Asia,India,2020-09-23,5646010.0,83347.0,89378.714,90020.0,1085.0,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64

In [18]:
india_df.drop(columns=['index', 'iso_code', 'continent'], inplace=True)

In [19]:
india_df

,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,India,2019-12-31,0.0,0.0,NaN,0.0,0.0,NaN,0.000,0.000,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
1,India,2020-01-01,0.0,0.0,NaN,0.0,0.0,NaN,0.000,0.000,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
2,India,2020-01-02,0.0,0.0,NaN,0.0,0.0,NaN,0.000,0.000,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
3,India,2020-01-03,0.0,0.0,NaN,0.0,0.0,NaN,0.000,0.000,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
4,India,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,0.000,0.000,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,India,2020-09-19,5308014.0,93337.0,92575.714,85619.0,1247.0,1163.857,3846.375,67.635,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
264,India,2020-09-20,5400619.0,92605.0,92323.286,86752.0,1133.0,1166.571,3913.480,67.105,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
265,India,2020-09-21,5487580.0,86961.0,91593.286,87882.0,1130.0,1165.714,3976.495,63.015,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
266,India,2020-09-22,5562663.0,75083.0,90346.714,88935.0,1053.0,1165.571,4030.902,54.408,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
267,India,2020-09-23,5646010.0,83347.0,89378.714,90020.0,1085.0,1136.286,4091.299,60.396,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64

In [20]:
india_df.drop(columns=['location'], inplace=True)

In [21]:
india_df

,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,2019-12-31,0.0,0.0,NaN,0.0,0.0,NaN,0.000,0.000,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
1,2020-01-01,0.0,0.0,NaN,0.0,0.0,NaN,0.000,0.000,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
2,2020-01-02,0.0,0.0,NaN,0.0,0.0,NaN,0.000,0.000,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
3,2020-01-03,0.0,0.0,NaN,0.0,0.0,NaN,0.000,0.000,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
4,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,0.000,0.000,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,2020-09-19,5308014.0,93337.0,92575.714,85619.0,1247.0,1163.857,3846.375,67.635,67.084,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
264,2020-09-20,5400619.0,92605.0,92323.286,86752.0,1133.0,1166.571,3913.480,67.105,66.901,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
265,2020-09-21,5487580.0,86961.0,91593.286,87882.0,1130.0,1165.714,3976.495,63.015,66.372,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
266,2020-09-22,5562663.0,75083.0,90346.714,88935.0,1053.0,1165.571,4030.902,54.408,65.468,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
267,2020-09-23,5646010.0,83347.0,89378.714,90020.0,1085.0,1136.286,4091.299,60.396,64.767,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64

In [22]:
india_df.to_csv('india.csv', index=None)

In [23]:
jovian.commit(outputs=['owid-covid-data.csv', 'india.csv'])

[jovian] Attempting to save notebook..
[jovian] Updating notebook "blazing-storm/india-covid-data-analysis" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Uploading additional outputs...
[jovian] Committed successfully! https://jovian.ml/blazing-storm/india-covid-data-analysis

'https://jovian.ml/blazing-storm/india-covid-data-analysis'

In [24]:
jovian.commit(outputs=['india.csv'])

[jovian] Attempting to save notebook..
[jovian] Updating notebook "blazing-storm/india-covid-data-analysis" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Uploading additional outputs...
[jovian] Committed successfully! https://jovian.ml/blazing-storm/india-covid-data-analysis

'https://jovian.ml/blazing-storm/india-covid-data-analysis'

In [25]:
india_df.columns

Index(['date', 'total_cases', 'new_cases', 'new_cases_smoothed',
       'total_deaths', 'new_deaths', 'new_deaths_smoothed',
       'total_cases_per_million', 'new_cases_per_million',
       'new_cases_smoothed_per_million', 'total_deaths_per_million',
       'new_deaths_per_million', 'new_deaths_smoothed_per_million',
       'new_tests', 'total_tests', 'total_tests_per_thousand',
       'new_tests_per_thousand', 'new_tests_smoothed',
       'new_tests_smoothed_per_thousand', 'tests_per_case', 'positive_rate',
       'tests_units', 'stringency_index', 'population', 'population_density',
       'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita',
       'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence',
       'female_smokers', 'male_smokers', 'handwashing_facilities',
       'hospital_beds_per_thousand', 'life_expectancy',
       'human_development_index'],
      dtype='object')

In [26]:
india_df['tests_units']

0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
            ...
263    samples tested
264    samples tested
265    samples tested
266               NaN
267               NaN
Name: tests_units, Length: 268, dtype: object

In [27]:
india_df['stringency_index']

0      NaN
1      0.0
2      0.0
3      0.0
4      0.0
      ...
263    NaN
264    NaN
265    NaN
266    NaN
267    NaN
Name: stringency_index, Length: 268, dtype: float64

In [28]:
india_df['total_tests_per_million']

KeyError: 'total_tests_per_million'

In [29]:
india_covid_df = india_df[['date',
                           'new_cases', 
                           'total_cases', 
                           'new_deaths', 
                           'total_deaths', 
                           'new_tests', 
                           'total_tests',
                           'total_cases_per_million', 
                           'total_deaths_per_million', 
                           'total_tests_per_thousand']]

In [30]:
india_covid_df

,date,new_cases,total_cases,new_deaths,total_deaths,new_tests,total_tests,total_cases_per_million,total_deaths_per_million,total_tests_per_thousand
0,2019-12-31,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN
1,2020-01-01,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN
2,2020-01-02,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN
3,2020-01-03,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN
4,2020-01-04,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN
...,...,...,...,...,...,...,...,...,...,...
263,2020-09-19,93337.0,5308014.0,1247.0,85619.0,1206806.0,63661060.0,3846.375,62.043,46.131
264,2020-09-20,92605.0,5400619.0,1133.0,86752.0,731534.0,64392594.0,3913.480,62.864,46.661
265,2020-09-21,86961.0,5487580.0,1130.0,87882.0,933185.0,65325779.0,3976.495,63.682,47.337
266,2020-09-22,75083.0,5562663.0,1053.0,88935.0,NaN,NaN,4030.902,64.445,NaN
267,2020-09-23,83347.0,5646010.0,1085.0,90020.0,NaN,NaN,4091.299,65.232,NaN

In [31]:
india_covid_df.to_csv('india-covid-daywise.csv', index=None)

In [ ]:
jovian.commit(project='india-covid-data-analysis', outputs=['india.csv', 'india-covid-daywise.csv'])

[jovian] Attempting to save notebook..