# India Covid Data Analysis
### Date - 24/09/2020

In [2]:
import pandas as pd

The source file was already uploaded in the notebook.

To read the file, we can use the `read_csv` method from Pandas. Let's being by importing the Pandas library. It is typically imported with the alias `pd`.

In [3]:
covid_df = pd.read_csv('india-covid-daywise.csv')

In [4]:
covid_df

,date,new_cases,total_cases,new_deaths,total_deaths,new_tests,total_tests,total_cases_per_million,total_deaths_per_million,total_tests_per_thousand
0,2019-12-31,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN
1,2020-01-01,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN
2,2020-01-02,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN
3,2020-01-03,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN
4,2020-01-04,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN
...,...,...,...,...,...,...,...,...,...,...
263,2020-09-19,93337.0,5308014.0,1247.0,85619.0,1206806.0,63661060.0,3846.375,62.043,46.131
264,2020-09-20,92605.0,5400619.0,1133.0,86752.0,731534.0,64392594.0,3913.480,62.864,46.661
265,2020-09-21,86961.0,5487580.0,1130.0,87882.0,933185.0,65325779.0,3976.495,63.682,47.337
266,2020-09-22,75083.0,5562663.0,1053.0,88935.0,NaN,NaN,4030.902,64.445,NaN
267,2020-09-23,83347.0,5646010.0,1085.0,90020.0,NaN,NaN,4091.299,65.232,NaN

In [5]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      268 non-null    object
 1   new_cases                 267 non-null    float64
 2   total_cases               267 non-null    float64
 3   new_deaths                267 non-null    float64
 4   total_deaths              267 non-null    float64
 5   new_tests                 176 non-null    float64
 6   total_tests               182 non-null    float64
 7   total_cases_per_million   267 non-null    float64
 8   total_deaths_per_million  267 non-null    float64
 9   total_tests_per_thousand  182 non-null    float64
dtypes: float64(9), object(1)
memory usage: 21.1+ KB

In [6]:
covid_df.describe()

,new_cases,total_cases,new_deaths,total_deaths,new_tests,total_tests,total_cases_per_million,total_deaths_per_million,total_tests_per_thousand
count,267.000000,2.670000e+02,267.000000,267.000000,1.760000e+02,1.820000e+02,267.000000,267.000000,182.000000
mean,21146.104869,8.749693e+05,337.153558,17049.966292,3.704028e+05,1.531253e+07,634.033640,12.355004,11.096016
std,29778.938431,1.456264e+06,412.699142,25077.536718,3.682234e+05,1.815944e+07,1055.260188,18.172053,13.158956
min,0.000000,0.000000e+00,0.000000,0.000000,1.570000e+02,6.500000e+03,0.000000,0.000000,0.005000
25%,2.000000,3.000000e+01,0.000000,0.000000,8.910025e+04,1.544669e+06,0.021500,0.000000,1.119500
50%,3900.000000,7.428100e+04,122.000000,2415.000000,2.090815e+05,7.245314e+06,53.827000,1.750000,5.250000
75%,36052.000000,1.058167e+06,651.000000,26544.500000,6.626562e+05,2.323748e+07,766.785000,19.235000,16.838500
max,97894.000000,5.646010e+06,2003.000000,90020.000000,1.206806e+06,6.532578e+07,4091.299000,65.232000,47.337000

In [7]:
covid_df.columns

Index(['date', 'new_cases', 'total_cases', 'new_deaths', 'total_deaths',
       'new_tests', 'total_tests', 'total_cases_per_million',
       'total_deaths_per_million', 'total_tests_per_thousand'],
      dtype='object')

In [8]:
covid_df.shape

(268, 10)

In [9]:
# Install the library 
!pip install jovian --upgrade --quiet

In [10]:
import jovian

# Retrieving data from a data frame

In [11]:
covid_df['new_cases']

0          0.0
1          0.0
2          0.0
3          0.0
4          0.0
        ...
263    93337.0
264    92605.0
265    86961.0
266    75083.0
267    83347.0
Name: new_cases, Length: 268, dtype: float64

In [12]:
type(covid_df['new_cases'])

pandas.core.series.Series

In [13]:
covid_df['new_cases'][265]

86961.0

In [14]:
covid_df.at[265, 'new_tests']

933185.0

In [15]:
cases_df = covid_df[['date', 'new_cases']]
cases_df

           date  new_cases
0    2019-12-31        0.0
1    2020-01-01        0.0
2    2020-01-02        0.0
3    2020-01-03        0.0
4    2020-01-04        0.0
..          ...        ...
263  2020-09-19    93337.0
264  2020-09-20    92605.0
265  2020-09-21    86961.0
266  2020-09-22    75083.0
267  2020-09-23    83347.0

[268 rows x 2 columns]

In [16]:
covid_df.loc[265]

date                         2020-09-21
new_cases                         86961
total_cases                 5.48758e+06
new_deaths                         1130
total_deaths                      87882
new_tests                        933185
total_tests                 6.53258e+07
total_cases_per_million         3976.49
total_deaths_per_million         63.682
total_tests_per_thousand         47.337
Name: 265, dtype: object

In [17]:
covid_df.tail(10)

,date,new_cases,total_cases,new_deaths,total_deaths,new_tests,total_tests,total_cases_per_million,total_deaths_per_million,total_tests_per_thousand
258,2020-09-14,92071.0,4846427.0,1136.0,79722.0,1072845.0,58312273.0,3511.892,57.769,42.255
259,2020-09-15,83809.0,4930236.0,1054.0,80776.0,1116842.0,59429115.0,3572.623,58.533,43.064
260,2020-09-16,90123.0,5020359.0,1290.0,82066.0,1136613.0,60565728.0,3637.930,59.468,43.888
261,2020-09-17,97894.0,5118253.0,1132.0,83198.0,1006615.0,61572343.0,3708.867,60.288,44.617
262,2020-09-18,96424.0,5214677.0,1174.0,84372.0,881911.0,62454254.0,3778.739,61.139,45.257
263,2020-09-19,93337.0,5308014.0,1247.0,85619.0,1206806.0,63661060.0,3846.375,62.043,46.131
264,2020-09-20,92605.0,5400619.0,1133.0,86752.0,731534.0,64392594.0,3913.480,62.864,46.661
265,2020-09-21,86961.0,5487580.0,1130.0,87882.0,933185.0,65325779.0,3976.495,63.682,47.337
266,2020-09-22,75083.0,5562663.0,1053.0,88935.0,NaN,NaN,4030.902,64.445,NaN
267,2020-09-23,83347.0,5646010.0,1085.0,90020.0,NaN,NaN,4091.299,65.232,NaN

In [18]:
covid_df.at[0, 'new_tests']

nan

In [19]:
type(covid_df.at[0, 'new_tests'])

numpy.float64

In [20]:
covid_df.new_tests.first_valid_index()

78

In [21]:
covid_df.loc[75:80]

,date,new_cases,total_cases,new_deaths,total_deaths,new_tests,total_tests,total_cases_per_million,total_deaths_per_million,total_tests_per_thousand
75,2020-03-15,7.0,90.0,0.0,2.0,NaN,NaN,0.065,0.001,NaN
76,2020-03-16,3.0,93.0,0.0,2.0,NaN,NaN,0.067,0.001,NaN
77,2020-03-17,32.0,125.0,1.0,3.0,NaN,13125.0,0.091,0.002,0.010
78,2020-03-18,12.0,137.0,0.0,3.0,191.0,13316.0,0.099,0.002,0.010
79,2020-03-19,28.0,165.0,0.0,3.0,1060.0,14376.0,0.120,0.002,0.010
80,2020-03-20,26.0,191.0,1.0,4.0,1325.0,15701.0,0.138,0.003,0.011

In [22]:
covid_df.sample(10)

,date,new_cases,total_cases,new_deaths,total_deaths,new_tests,total_tests,total_cases_per_million,total_deaths_per_million,total_tests_per_thousand
14,2020-01-14,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN
225,2020-08-12,60963.0,2329638.0,834.0,46091.0,830391.0,26845688.0,1688.138,33.399,19.453
192,2020-07-10,26506.0,793802.0,475.0,21604.0,282511.0,11307002.0,575.217,15.655,8.193
182,2020-06-30,18522.0,566840.0,418.0,16893.0,217931.0,8826585.0,410.752,12.241,6.396
9,2020-01-09,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN
2,2020-01-02,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN
189,2020-07-07,22252.0,719665.0,467.0,20160.0,262679.0,10473771.0,521.495,14.609,7.590
165,2020-06-13,11458.0,308993.0,386.0,8884.0,151432.0,5658614.0,223.907,6.438,4.100
205,2020-07-23,45720.0,1238635.0,1129.0,29861.0,352801.0,15428170.0,897.559,21.638,11.180
241,2020-08-28,77266.0,3387500.0,1057.0,61529.0,928761.0,40406609.0,2454.702,44.586,29.280

# Analyzing Data from data frames
Let's try to answer some questions about our data.

**Q: What is the total number of reported cases and deaths related to Covid-19 in India?**

In [23]:
total_cases = covid_df.new_cases.sum()
total_deaths = covid_df.new_deaths.sum()
print('The number of reported cases is {} and the number of reported deaths is {}.'.format(int(total_cases), int(total_deaths)))

The number of reported cases is 5646010 and the number of reported deaths is 90020.

**Q: What is the overall death rate (ratio of reported deats to reported cases)?**

In [24]:
death_rate = covid_df.new_deaths.sum() / covid_df.new_cases.sum()
print("The overall reported death rate in Italy is {:.2f} %.".format(death_rate*100))

The overall reported death rate in Italy is 1.59 %.

**Q: What fraction of tests returned a postive result?**

In [25]:
total_tests = covid_df.new_tests.sum()

In [26]:
positive_rate = total_cases / total_tests
print('{:.2f}% of tests in Italy led to a positive diagnosis.'.format(positive_rate*100))

8.66% of tests in Italy led to a positive diagnosis.

In [27]:
jovian.commit(project='india-covid-data-analysis')

[jovian] Attempting to save notebook..
[jovian] Updating notebook "blazing-storm/india-covid-data-analysis" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/blazing-storm/india-covid-data-analysis

'https://jovian.ml/blazing-storm/india-covid-data-analysis'

# Querying and sorting rows

In [29]:
high_cases_df = covid_df[covid_df.new_cases > 50000]
high_cases_df

,date,new_cases,total_cases,new_deaths,total_deaths,new_tests,total_tests,total_cases_per_million,total_deaths_per_million,total_tests_per_thousand
212,2020-07-30,52123.0,1583792.0,775.0,34968.0,642588.0,18832970.0,1147.672,25.339,13.647
213,2020-07-31,55078.0,1638870.0,779.0,35747.0,525689.0,19358659.0,1187.583,25.904,14.028
214,2020-08-01,57118.0,1695988.0,764.0,36511.0,463172.0,19821831.0,1228.973,26.457,14.364
215,2020-08-02,54735.0,1750723.0,853.0,37364.0,381027.0,20202858.0,1268.636,27.075,14.640
216,2020-08-03,52972.0,1803695.0,771.0,38135.0,661892.0,20864750.0,1307.021,27.634,15.119
217,2020-08-04,52050.0,1855745.0,803.0,38938.0,619652.0,21484402.0,1344.738,28.216,15.568
218,2020-08-05,52509.0,1908254.0,857.0,39795.0,664949.0,22149351.0,1382.788,28.837,16.050
219,2020-08-06,56282.0,1964536.0,904.0,40699.0,639042.0,22788393.0,1423.572,29.492,16.513
220,2020-08-07,62538.0,2027074.0,886.0,41585.0,598778.0,23387171.0,1468.890,30.134,16.947
221,2020-08-08,61537.0,2088611.0,933.0,42518.0,719364.0,24106535.0,1513.481,30.810,17.468
222,2020-08-09,64399.0,2153010.0,861.0,43379.0,477023.0,24583558.0,1560.147,31.434,17.814
223,2020-08-10,62064.0,2215074.0,1007.0,44386.0,698290.0,25281848.0,1605.121,32.164,18.320
224,2020-08-11,53601.0,2268675.0,871.0,45257.0,733449.0,26015297.0,1643.962,32.795,18.852
225,2020-08-12,60963.0,2329638.0,834.0,46091.0,830391.0,26845688.0,1688.138,33.399,19.453
226,2020-08-13,66999.0,2396637.0,942.0,47033.0,848728.0,27694416.0,1736.688,34.082,20.068
227,2020-08-14,64553.0,2461190.0,1007.0,48040.0,868679.0,28563095.0,1783.465,34.811,20.698
228,2020-08-15,65002.0,2526192.0,996.0,49036.0,746608.0,29309703.0,1830.568,35.533,21.239
229,2020-08-16,63490.0,2589682.0,944.0,49980.0,731697.0,30041400.0,1876.575,36.217,21.769
230,2020-08-17,57981.0,2647663.0,941.0,50921.0,899864.0,30941264.0,1918.590,36.899,22.421
231,2020-08-18,55079.0,2702742.0,876.0,51797.0,801518.0,31742782.0,1958.502,37.534,23.002
232,2020-08-19,64531.0,2767273.0,1092.0,52889.0,918470.0,32661252.0,2005.264,38.325,23.667
233,2020-08-20,69652.0,2836925.0,977.0,53866.0,805985.0,33467237.0,2055.736,39.033,24.252
234,2020-08-21,68898.0,2905823.0,983.0,54849.0,1023836.0,34491073.0,2105.662,39.746,24.993
235,2020-08-22,69878.0,2975701.0,945.0,55794.0,801147.0,35292220.0,2156.298,40.430,25.574
236,2020-08-23,69239.0,3044940.0,912.0,56706.0,609917.0,35902137.0,2206.471,41.091,26.016
237,2020-08-24,61408.0,3106348.0,836.0,57542.0,925383.0,36827520.0,2250.970,41.697,26.687
238,2020-08-25,60975.0,3167323.0,848.0,58390.0,823992.0,37651512.0,2295.154,42.311,27.284
239,2020-08-26,67151.0,3234474.0,1059.0,59449.0,924998.0,38576510.0,2343.814,43.079,27.954
240,2020-08-27,75760.0,3310234.0,1023.0,60472.0,901338.0,39477848.0,2398.713,43.820,28.607
241,2020-08-28,77266.0,3387500.0,1057.0,61529.0,928761.0,40406609.0,2454.702,44.586,29.280
242,2020-08-29,76472.0,3463972.0,1021.0,62550.0,1055027.0,41461636.0,2510.117,45.326,30.045
243,2020-08-30,78761.0,3542733.0,948.0,63498.0,846278.0,42307914.0,2567.190,46.013,30.658
244,2020-08-31,78512.0,3621245.0,971.0,64469.0,1016920.0,43324834.0,2624.082,46.717,31.395
245,2020-09-01,69921.0,3691166.0,759.0,65228.0,1012367.0,44337201.0,2674.749,47.267,32.128
246,2020-09-02,78357.0,3769523.0,1105.0,66333.0,1172179.0,45509380.0,2731.530,48.067,32.978
247,2020-09-03,83883.0,3853406.0,1043.0,67376.0,1169765.0,46679145.0,2792.314,48.823,33.825
248,2020-09-04,83341.0,3936747.0,1096.0,68472.0,1059346.0,47738491.0,2852.706,49.617,34.593
249,2020-09-05,86432.0,4023179.0,1089.0,69561.0,1092654.0,48831145.0,2915.338,50.406,35.385
250,2020-09-06,90632.0,4113811.0,1065.0,70626.0,720362.0,49551507.0,2981.013,51.178,35.907
251,2020-09-07,90802.0,4204613.0,1016.0,71642.0,1098621.0,50650128.0,3046.811,51.914,36.703
252,2020-09-08,75809.0,4280422.0,1133.0,72775.0,1154549.0,51804677.0,3101.745,52.735,37.540
253,2020-09-09,89706.0,4370128.0,1115.0,73890.0,1129756.0,52934433.0,3166.749,53.543,38.358
254,2020-09-10,95735.0,4465863.0,1172.0,75062.0,1163542.0,54097975.0,3236.122,54.393,39.201
255,2020-09-11,96551.0,4562414.0,1209.0,76271.0,1091251.0,55189226.0,3306.087,55.269,39.992
256,2020-09-12,97570.0,4659984.0,1201.0,77472.0,1071702.0,56260928.0,3376.789,56.139,40.769
257,2020-09-13,94372.0,4754356.0,1114.0,78586.0,978500.0,57239428.0,3445.175,56.946,41.478
258,2020-09-14,92071.0,4846427.0,1136.0,79722.0,1072845.0,58312273.0,3511.892,57.769,42.255
259,2020-09-15,83809.0,4930236.0,1054.0,80776.0,1116842.0,59429115.0,3572.623,58.533,43.064
260,2020-09-16,90123.0,5020359.0,1290.0,82066.0,1136613.0,60565728.0,3637.930,59.468,43.888
261,2020-09-17,97894.0,5118253.0,1132.0,83198.0,1006615.0,61572343.0,3708.867,60.288,44.617
262,2020-09-18,96424.0,5214677.0,1174.0,84372.0,881911.0,62454254.0,3778.739,61.139,45.257
263,2020-09-19,93337.0,5308014.0,1247.0,85619.0,1206806.0,63661060.0,3846.375,62.043,46.131
264,2020-09-20,92605.0,5400619.0,1133.0,86752.0,731534.0,64392594.0,3913.480,62.864,46.661
265,2020-09-21,86961.0,5487580.0,1130.0,87882.0,933185.0,65325779.0,3976.495,63.682,47.337
266,2020-09-22,75083.0,5562663.0,1053.0,88935.0,NaN,NaN,4030.902,64.445,NaN
267,2020-09-23,83347.0,5646010.0,1085.0,90020.0,NaN,NaN,4091.299,65.232,NaN

In [30]:
positive_rate

0.08660734518876265

In [31]:
high_ratio_df = covid_df[covid_df.new_cases / covid_df.new_tests > positive_rate]
high_ratio_df

,date,new_cases,total_cases,new_deaths,total_deaths,new_tests,total_tests,total_cases_per_million,total_deaths_per_million,total_tests_per_thousand
83,2020-03-23,119.0,439.0,3.0,7.0,157.0,20864.0,0.318,0.005,0.015
159,2020-06-07,9971.0,246628.0,287.0,6929.0,108048.0,4774434.0,178.715,5.021,3.460
166,2020-06-14,11929.0,320922.0,311.0,9195.0,115519.0,5774133.0,232.551,6.663,4.184
173,2020-06-21,15413.0,410461.0,306.0,13254.0,143267.0,6950493.0,297.435,9.604,5.037
180,2020-06-28,19906.0,528859.0,410.0,16095.0,170560.0,8398362.0,383.230,11.663,6.086
181,2020-06-29,19459.0,548318.0,380.0,16475.0,210292.0,8608654.0,397.331,11.938,6.238
186,2020-07-04,22771.0,648315.0,442.0,18655.0,248934.0,9789066.0,469.792,13.518,7.094
187,2020-07-05,24850.0,673165.0,613.0,19268.0,180596.0,9969662.0,487.799,13.962,7.224
188,2020-07-06,24248.0,697413.0,425.0,19693.0,241430.0,10211092.0,505.370,14.270,7.399
191,2020-07-09,24879.0,767296.0,487.0,21129.0,283659.0,11024491.0,556.010,15.311,7.989
192,2020-07-10,26506.0,793802.0,475.0,21604.0,282511.0,11307002.0,575.217,15.655,8.193
193,2020-07-11,27114.0,820916.0,519.0,22123.0,280151.0,11587153.0,594.865,16.031,8.396
194,2020-07-12,28637.0,849553.0,551.0,22674.0,219103.0,11806256.0,615.616,16.430,8.555
195,2020-07-13,28701.0,878254.0,500.0,23174.0,286247.0,12092503.0,636.414,16.793,8.763
196,2020-07-14,28498.0,906752.0,553.0,23727.0,320161.0,12412664.0,657.065,17.193,8.995
197,2020-07-15,29429.0,936181.0,582.0,24309.0,326826.0,12739490.0,678.390,17.615,9.231
198,2020-07-16,32695.0,968876.0,606.0,24915.0,333228.0,13072718.0,702.082,18.054,9.473
199,2020-07-17,34956.0,1003832.0,687.0,25602.0,361024.0,13433742.0,727.412,18.552,9.735
200,2020-07-18,34884.0,1038716.0,671.0,26273.0,358127.0,13791869.0,752.690,19.038,9.994
201,2020-07-19,38902.0,1077618.0,543.0,26816.0,256039.0,14047908.0,780.880,19.432,10.180
202,2020-07-20,40425.0,1118043.0,681.0,27497.0,333395.0,14381303.0,810.174,19.925,10.421
203,2020-07-21,37148.0,1155191.0,587.0,28084.0,343243.0,14724546.0,837.092,20.351,10.670
204,2020-07-22,37724.0,1192915.0,648.0,28732.0,350823.0,15075369.0,864.428,20.820,10.924
205,2020-07-23,45720.0,1238635.0,1129.0,29861.0,352801.0,15428170.0,897.559,21.638,11.180
206,2020-07-24,49310.0,1287945.0,740.0,30601.0,420898.0,15849068.0,933.291,22.175,11.485
207,2020-07-25,48916.0,1336861.0,757.0,31358.0,442263.0,16291331.0,968.737,22.723,11.805
208,2020-07-26,48661.0,1385522.0,705.0,32063.0,515472.0,16806803.0,1003.998,23.234,12.179
209,2020-07-27,49931.0,1435453.0,708.0,32771.0,528082.0,17334885.0,1040.180,23.747,12.561
210,2020-07-28,47703.0,1483156.0,654.0,33425.0,408855.0,17743740.0,1074.747,24.221,12.858
211,2020-07-29,48513.0,1531669.0,768.0,34193.0,446642.0,18190382.0,1109.902,24.777,13.181
213,2020-07-31,55078.0,1638870.0,779.0,35747.0,525689.0,19358659.0,1187.583,25.904,14.028
214,2020-08-01,57118.0,1695988.0,764.0,36511.0,463172.0,19821831.0,1228.973,26.457,14.364
215,2020-08-02,54735.0,1750723.0,853.0,37364.0,381027.0,20202858.0,1268.636,27.075,14.640
219,2020-08-06,56282.0,1964536.0,904.0,40699.0,639042.0,22788393.0,1423.572,29.492,16.513
220,2020-08-07,62538.0,2027074.0,886.0,41585.0,598778.0,23387171.0,1468.890,30.134,16.947
222,2020-08-09,64399.0,2153010.0,861.0,43379.0,477023.0,24583558.0,1560.147,31.434,17.814
223,2020-08-10,62064.0,2215074.0,1007.0,44386.0,698290.0,25281848.0,1605.121,32.164,18.320
228,2020-08-15,65002.0,2526192.0,996.0,49036.0,746608.0,29309703.0,1830.568,35.533,21.239
229,2020-08-16,63490.0,2589682.0,944.0,49980.0,731697.0,30041400.0,1876.575,36.217,21.769
235,2020-08-22,69878.0,2975701.0,945.0,55794.0,801147.0,35292220.0,2156.298,40.430,25.574
236,2020-08-23,69239.0,3044940.0,912.0,56706.0,609917.0,35902137.0,2206.471,41.091,26.016
243,2020-08-30,78761.0,3542733.0,948.0,63498.0,846278.0,42307914.0,2567.190,46.013,30.658
250,2020-09-06,90632.0,4113811.0,1065.0,70626.0,720362.0,49551507.0,2981.013,51.178,35.907
255,2020-09-11,96551.0,4562414.0,1209.0,76271.0,1091251.0,55189226.0,3306.087,55.269,39.992
256,2020-09-12,97570.0,4659984.0,1201.0,77472.0,1071702.0,56260928.0,3376.789,56.139,40.769
257,2020-09-13,94372.0,4754356.0,1114.0,78586.0,978500.0,57239428.0,3445.175,56.946,41.478
261,2020-09-17,97894.0,5118253.0,1132.0,83198.0,1006615.0,61572343.0,3708.867,60.288,44.617
262,2020-09-18,96424.0,5214677.0,1174.0,84372.0,881911.0,62454254.0,3778.739,61.139,45.257
264,2020-09-20,92605.0,5400619.0,1133.0,86752.0,731534.0,64392594.0,3913.480,62.864,46.661
265,2020-09-21,86961.0,5487580.0,1130.0,87882.0,933185.0,65325779.0,3976.495,63.682,47.337

## Sorting rows using column values

In [32]:
covid_df.sort_values('new_cases', ascending=False).head(10)

,date,new_cases,total_cases,new_deaths,total_deaths,new_tests,total_tests,total_cases_per_million,total_deaths_per_million,total_tests_per_thousand
261,2020-09-17,97894.0,5118253.0,1132.0,83198.0,1006615.0,61572343.0,3708.867,60.288,44.617
256,2020-09-12,97570.0,4659984.0,1201.0,77472.0,1071702.0,56260928.0,3376.789,56.139,40.769
255,2020-09-11,96551.0,4562414.0,1209.0,76271.0,1091251.0,55189226.0,3306.087,55.269,39.992
262,2020-09-18,96424.0,5214677.0,1174.0,84372.0,881911.0,62454254.0,3778.739,61.139,45.257
254,2020-09-10,95735.0,4465863.0,1172.0,75062.0,1163542.0,54097975.0,3236.122,54.393,39.201
257,2020-09-13,94372.0,4754356.0,1114.0,78586.0,978500.0,57239428.0,3445.175,56.946,41.478
263,2020-09-19,93337.0,5308014.0,1247.0,85619.0,1206806.0,63661060.0,3846.375,62.043,46.131
264,2020-09-20,92605.0,5400619.0,1133.0,86752.0,731534.0,64392594.0,3913.480,62.864,46.661
258,2020-09-14,92071.0,4846427.0,1136.0,79722.0,1072845.0,58312273.0,3511.892,57.769,42.255
251,2020-09-07,90802.0,4204613.0,1016.0,71642.0,1098621.0,50650128.0,3046.811,51.914,36.703

In [33]:
covid_df.sort_values('new_deaths', ascending=False).head(10)

,date,new_cases,total_cases,new_deaths,total_deaths,new_tests,total_tests,total_cases_per_million,total_deaths_per_million,total_tests_per_thousand
169,2020-06-17,10974.0,354065.0,2003.0,11903.0,165412.0,6249668.0,256.568,8.625,4.529
260,2020-09-16,90123.0,5020359.0,1290.0,82066.0,1136613.0,60565728.0,3637.930,59.468,43.888
263,2020-09-19,93337.0,5308014.0,1247.0,85619.0,1206806.0,63661060.0,3846.375,62.043,46.131
255,2020-09-11,96551.0,4562414.0,1209.0,76271.0,1091251.0,55189226.0,3306.087,55.269,39.992
256,2020-09-12,97570.0,4659984.0,1201.0,77472.0,1071702.0,56260928.0,3376.789,56.139,40.769
262,2020-09-18,96424.0,5214677.0,1174.0,84372.0,881911.0,62454254.0,3778.739,61.139,45.257
254,2020-09-10,95735.0,4465863.0,1172.0,75062.0,1163542.0,54097975.0,3236.122,54.393,39.201
258,2020-09-14,92071.0,4846427.0,1136.0,79722.0,1072845.0,58312273.0,3511.892,57.769,42.255
252,2020-09-08,75809.0,4280422.0,1133.0,72775.0,1154549.0,51804677.0,3101.745,52.735,37.540
264,2020-09-20,92605.0,5400619.0,1133.0,86752.0,731534.0,64392594.0,3913.480,62.864,46.661

In [34]:
covid_df.sort_values('new_cases').head(10)

,date,new_cases,total_cases,new_deaths,total_deaths,new_tests,total_tests,total_cases_per_million,total_deaths_per_million,total_tests_per_thousand
0,2019-12-31,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.0,NaN
32,2020-02-01,0.0,1.0,0.0,0.0,NaN,NaN,0.001,0.0,NaN
62,2020-03-02,0.0,3.0,0.0,0.0,NaN,NaN,0.002,0.0,NaN
34,2020-02-03,0.0,2.0,0.0,0.0,NaN,NaN,0.001,0.0,NaN
61,2020-03-01,0.0,3.0,0.0,0.0,NaN,NaN,0.002,0.0,NaN
36,2020-02-05,0.0,3.0,0.0,0.0,NaN,NaN,0.002,0.0,NaN
37,2020-02-06,0.0,3.0,0.0,0.0,NaN,NaN,0.002,0.0,NaN
38,2020-02-07,0.0,3.0,0.0,0.0,NaN,NaN,0.002,0.0,NaN
39,2020-02-08,0.0,3.0,0.0,0.0,NaN,NaN,0.002,0.0,NaN
40,2020-02-09,0.0,3.0,0.0,0.0,NaN,NaN,0.002,0.0,NaN

In [35]:
jovian.commit()

[jovian] Attempting to save notebook..
[jovian] Updating notebook "blazing-storm/india-covid-data-analysis" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/blazing-storm/india-covid-data-analysis

'https://jovian.ml/blazing-storm/india-covid-data-analysis'

## Working with dates

In [36]:
covid_df.date

0      2019-12-31
1      2020-01-01
2      2020-01-02
3      2020-01-03
4      2020-01-04
          ...
263    2020-09-19
264    2020-09-20
265    2020-09-21
266    2020-09-22
267    2020-09-23
Name: date, Length: 268, dtype: object

The data type of date is currently `object`, so Pandas does not know that this column is a date. We can convert it into a `datetime` column using the `pd.to_datetime` method.

In [37]:
covid_df['date'] = pd.to_datetime(covid_df.date)
covid_df['date']

0     2019-12-31
1     2020-01-01
2     2020-01-02
3     2020-01-03
4     2020-01-04
         ...
263   2020-09-19
264   2020-09-20
265   2020-09-21
266   2020-09-22
267   2020-09-23
Name: date, Length: 268, dtype: datetime64[ns]

In [38]:
covid_df['month'] = pd.DatetimeIndex(covid_df.date).month

In [39]:
covid_df

,date,new_cases,total_cases,new_deaths,total_deaths,new_tests,total_tests,total_cases_per_million,total_deaths_per_million,total_tests_per_thousand,month
0,2019-12-31,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN,12
1,2020-01-01,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN,1
2,2020-01-02,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN,1
3,2020-01-03,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN,1
4,2020-01-04,0.0,0.0,0.0,0.0,NaN,NaN,0.000,0.000,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...
263,2020-09-19,93337.0,5308014.0,1247.0,85619.0,1206806.0,63661060.0,3846.375,62.043,46.131,9
264,2020-09-20,92605.0,5400619.0,1133.0,86752.0,731534.0,64392594.0,3913.480,62.864,46.661,9
265,2020-09-21,86961.0,5487580.0,1130.0,87882.0,933185.0,65325779.0,3976.495,63.682,47.337,9
266,2020-09-22,75083.0,5562663.0,1053.0,88935.0,NaN,NaN,4030.902,64.445,NaN,9
267,2020-09-23,83347.0,5646010.0,1085.0,90020.0,NaN,NaN,4091.299,65.232,NaN,9

In [41]:
# Query the rows for August
covid_df_aug = covid_df[covid_df.month == 8]

# Extract the subset of columns to be aggregated
covid_df_aug_metrics = covid_df_aug[['new_cases', 'new_deaths', 'new_tests']]

# Get the column-wise sum
covid_aug_totals = covid_df_aug_metrics.sum()

In [42]:
covid_aug_totals

new_cases      1982375.0
new_deaths       28722.0
new_tests     23966175.0
dtype: float64

In [43]:
covid_df[covid_df.month == 8][['new_cases', 'new_deaths', 'new_tests']].sum()

new_cases      1982375.0
new_deaths       28722.0
new_tests     23966175.0
dtype: float64

In [44]:
jovian.commit()

[jovian] Attempting to save notebook..
[jovian] Updating notebook "blazing-storm/india-covid-data-analysis" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/blazing-storm/india-covid-data-analysis

'https://jovian.ml/blazing-storm/india-covid-data-analysis'